"""Configuración central del proyecto."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "datos"
STATIONS_FILE = DATA_DIR / "estaciones.json"
ASSETS_DIR = PROJECT_ROOT / "assets"
PROVINCES_GEOJSON = ASSETS_DIR / "argentina_provincias.geojson"
OUTPUT_DIR = PROJECT_ROOT / "output"
OUTPUT_HTML = OUTPUT_DIR / "index.html"
OUTPUT_PARQUET = OUTPUT_DIR / "datos_normalizados.parquet"
OUTPUT_AUDIT = OUTPUT_DIR / "auditoria.json"
OUTPUT_IDW_EVALUATION = OUTPUT_DIR / "evaluacion_idw.json"

TARGET_CRS = "EPSG:4326"
ARGENTINA_CENTER = (-38.4161, -63.6167)
DEFAULT_ZOOM = 4
PRECIPITATION_MIN = 0.0
PRECIPITATION_STEP = 10.0
INTERPOLATION_METHOD = "idw"
GRID_RESOLUTION = 0.5
IDW_POWER = 2.0
MIN_INTERPOLATION_STATIONS = 3
MAX_INTERPOLATION_DISTANCE_KM = 350.0
COVERAGE_RADIUS_KM = 250.0
GEOJSON_SIMPLIFICATION_TOLERANCE = 0.01
AGGREGATION_METHOD = "sum"

# Normal climatológica configurable. 1991–2020 sigue el período estándar de 30 años de la OMM.
CLIMATOLOGY_START_YEAR = 1991
CLIMATOLOGY_END_YEAR = 2020
MIN_HISTORICAL_YEARS = 5
RELATIVE_ANOMALY_COLOR_LIMIT = 200.0
